### ISSUE TITLE
Chromedriver freaks out

### ISSUE THREAD

**Issue by SEJeff** [cobrateam/splinter#322]
When doing some unit testing of an internal webapp using splinter and I insert a pdb into the test to verify the dom, I often get this if the window is resized or moved:

**\* WebDriverException: Message: u"unknown error: Runtime.evaluate threw exception: TypeError: Cannot read property 'click' of null\n  (Session info: chrome=35.0.1916.114)\n  (Driver info: chromedriver=2.9.248304,platform=Linux 3.8.5-201.fc18.x86_64 x86_64)" 

From then on, I'm unable to do anything and have to close the window + restart the tests.

**Comment by Jai008** [comment]
For me, when I execute automation scripts, getting this error for only css, works fine with xpath expression. not getting root cause, please help me.. below is the error

Exception occured during execution : unknown error: Cannot read property 'click' of null
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
