### ISSUE TITLE
chrome web driver: Use custom profile (also called user data directory)

### ISSUE THREAD

**Issue by HughGrant** [cobrateam/splinter#325]
how to do Use custom profile (also called user data directory)
I found these two line of code on google.
ChromeOptions options = new ChromeOptions();
options.addArguments("user-data-dir=/path/to/your/custom/profile");

How to do this by Splinter?

**Comment by olala7846** [comment]
+1 found the same problem

**Comment by myme5261314** [comment]
so, it seems 2 years later, this bug is still there, since I just checked the code again. I think I'd better choose `selenium` to use.

**Comment by douglascamata** [comment]
I think it would be better to contribute to the community and help everybody, wouldn't it?

**Comment by myme5261314** [comment]
yes, but by current code design structure, it's not that easy to add the fix code in place. Since I haven't used this library before today. It will be better for someone who's familiar with this library to come up with a better commit. The key for the fix is to remain a interface for user to customize the option.
By the way, just share to anyone who would face the same extra  issue I found today, if you open chrome with your user profile, then using selenium or splinter to the same profile directory will cause error, since it can be occupied by single instance. The workaround is either make a new profile copy and use new copy or close current chrome instance and its background service.

Wish this will help someone since it takes me a few time to fix this extra issue.

发自我的 iPhone

**Comment by jeverling** [comment]
I do it like this, it works fine for me: `options.add_argument('--user-data-dir=/home/jeverling/chrome_userdata')`
