### ISSUE TITLE
Inconsistent redirect behavior between browsers

### ISSUE THREAD

**Issue by symroe** [cobrateam/splinter#375]
I'm using splinter with Lettuce, more or less as outlined in [this post](http://cilliano.com/2011/02/07/django-bdd-with-lettuce-and-splinter.html).

I am using the following code to call a django view that returns a `301`:

`world.browser.visit(django_url('/url_that_returns_a_301/'))`

And then asserting:

`assert world.browser.status_code.code == 301`

If I use the `firefox` webdriver (`world.browser = Browser('firefox')`) the status code is indeed `301`, however if I change the browser to django (`world.browser = Browser('django')`) the status code is `200`, because the redirect has been followed.

This is clearly because the django driver is doing:

`self._response = self._browser.get(url, follow=True)`

However, I would expect a compatible API between drivers.

Can I suggest one or both of the following:

1. Removing the `follow=True` form the django driver to make it act more like firefox.
2. Add an optional argument `follow` to `visit`, giving the tester the control over this.

I would be happy to do the latter in a PR, but I'd like to know if there is a reason for this.

**Comment by cjkeeney** [comment]
I think this is more broken than your issue suggests.  I am using the FlaskDriver, and I have a signup controller with a form on it on Controller1.  The form has no action attribute.  When FlaskDriver submits the form, it properly submits to Controller1.  When the form processes successfully, it returns a 301 redirect to the next step in the signup process (also a form with no action attribute) Controller2.  
**At this point, the driver's html property is the html for Controller2, but the driver's url property is the url for Controller1**.  When this form gets submitted, the form is actually submitted to Controller1 instead of Controller2.

This is likely related to some combination of your issue and #309.
