### ISSUE TITLE
Capture Javascript errors (javascript console)

### ISSUE THREAD

**Issue by luzfcb** [cobrateam/splinter#405]
it is possible capture any text from javascript console?
I need to have some way to get Javascript errors.

**Comment by neo-inuit** [comment]
+1

**Comment by d3ming** [comment]
:+1:  would love to have this

**Comment by ecesena** [comment]
+1

**Comment by thebao** [comment]
+1

**Comment by vectorfrog** [comment]
There's a couple of different ways to accomplish this.  Check out this stack overflow thread:

[http://stackoverflow.com/questions/4189312/capturing-javascript-error-in-selenium](http://stackoverflow.com/questions/4189312/capturing-javascript-error-in-selenium)

**Comment by jsfehler** [comment]
Closing this, since it's a selenium issue, not splinter. I don't think we can provide a simpler way than what's already available.

https://www.selenium.dev/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver.get_log

The above method is currently the correct way to get logs using selenium, but this may change with their BiDi API.
