### ISSUE TITLE
On windows splinter 0.7.5 installed selenium 3.0.1 but it seems that this selenium is not supported by splinter

### ISSUE THREAD

**Issue by GeorgeFischhof** [cobrateam/splinter#524]
Hi There,

On windows splinter 0.7.5 installed selenium 3.0.1 but it seems that this selenium is not supported by splinter

when I replaced selenium to 2.53.6, there was no error

used: 
python 3.5.1 (32 bit)
firefox browser
command pip install --upgrade splinter

when I wanted visit url error message is displayed:

browser().visit('http://google.com')
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\selenium\webdriver\
common\service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Program Files (x86)\Python35-32\lib\subprocess.py", line 950, in __in
it__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Python35-32\lib\subprocess.py", line 1220, in _ex
ecute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\splinter\browser.py
", line 63, in Browser
    return driver(*args, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\splinter\driver\web
driver\firefox.py", line 48, in __init__
    timeout=timeout)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\selenium\webdriver\
firefox\webdriver.py", line 135, in __init__
    self.service.start()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\selenium\webdriver\
common\service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable
 needs to be in PATH.

BR,
George

**Comment by minhhuynguyen91** [comment]
FYI, Hi, the older version seems to work for me. I'm using:
+ OS: Ubuntu 16.04
+ Splinter: 0.7.3
+ Selenium: 2.53.6

**Comment by ggarcia24** [comment]
Actually I believe that this bug is related to the pip install requirements:

If your Selenium version is greater that 3.0, that means that you need the [geckodriver](https://github.com/mozilla/geckodriver), and thus the DesiredCapabilities must have the 'marionette' attribute as True (change present on splinter 0.7.6)

If you have selenium lower than 3.0 (i.e 2.53) you will be forced to have the marionette in False, and to use a Firefox version not greater than 47, as newer Firefox require you to use the Marionette driver.

At least that's my experience ;-). Is there a way that we can solve this? Can the required version for selenium be lower? I understand that now is set to be '>=3.4.3' but I'm aiming for '>=3.0.2', is there a way that we can change splinter 0.7.5 to explicitly require a version '<=2.53.6'?

**Comment by GeorgeFischhof** [comment]
Hi Folks,

if this is the situation, I think it should be documented in the user manual:
If you have firefox verison a.b.c then use selenium d.e.f and splinter g.h.i
If you have firefox verison a2.b2.c2 then use selenium d2.e2.f2 and splinter g2.h2.i2

;-)

BR,
George
